"""Add role to User

Revision ID: 146f463bdb26
Revises: a2161c458b01
Create Date: 2026-06-09 13:03:14.985752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '146f463bdb26'
down_revision: Union[str, None] = 'a2161c458b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column as nullable first to allow existing rows to populate
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True, server_default='player'))

    # Update existing rows based on is_admin status
    op.execute("UPDATE user SET role = 'admin' WHERE is_admin = 1")
    op.execute("UPDATE user SET role = 'player' WHERE is_admin = 0 OR is_admin IS NULL")



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
