"""Add tournament formats and tracking fields

Revision ID: f695e97cf8fd
Revises: 146f463bdb26
Create Date: 2026-06-09 13:23:12.910223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f695e97cf8fd'
down_revision: Union[str, None] = '146f463bdb26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tournamentformat',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('format_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('groups_count', sa.Integer(), nullable=False),
        sa.Column('gold_qualifiers', sa.Integer(), nullable=False),
        sa.Column('silver_qualifiers', sa.Integer(), nullable=False),
        sa.Column('bronze_qualifiers', sa.Integer(), nullable=False),
        sa.Column('has_third_place', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='groups'))
        batch_op.add_column(sa.Column('group_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('cup_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('round_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tournament_format', 'tournamentformat', ['format_id'], ['id'])

    with op.batch_alter_table('tournamentregistration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'player'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'player'"))

    with op.batch_alter_table('tournamentregistration', schema=None) as batch_op:
        batch_op.drop_column('group_label')

    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tournament_format', type_='foreignkey')
        batch_op.drop_column('format_id')

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('round_name')
        batch_op.drop_column('cup_name')
        batch_op.drop_column('group_label')
        batch_op.drop_column('stage')

    op.drop_table('tournamentformat')
    # ### end Alembic commands ###
